[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.13"

# Polygon Amoy Testnet Configuration
[rpc_endpoints]
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"

[etherscan]
polygon_amoy = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
